"""Top 250 US cities by population (2020 census + estimates).

Used for arrest-data coverage audit. Each entry: (city, state, pop_rank).
"""
from __future__ import annotations

from typing import List, Tuple

# (city, state_abbrev)
TOP_250_CITIES: List[Tuple[str, str]] = [
    ("New York", "NY"), ("Los Angeles", "CA"), ("Chicago", "IL"),
    ("Houston", "TX"), ("Phoenix", "AZ"), ("Philadelphia", "PA"),
    ("San Antonio", "TX"), ("San Diego", "CA"), ("Dallas", "TX"),
    ("Jacksonville", "FL"), ("Austin", "TX"), ("Fort Worth", "TX"),
    ("San Jose", "CA"), ("Columbus", "OH"), ("Charlotte", "NC"),
    ("Indianapolis", "IN"), ("San Francisco", "CA"), ("Seattle", "WA"),
    ("Denver", "CO"), ("Oklahoma City", "OK"), ("Nashville", "TN"),
    ("El Paso", "TX"), ("Washington", "DC"), ("Boston", "MA"),
    ("Las Vegas", "NV"), ("Portland", "OR"), ("Memphis", "TN"),
    ("Louisville", "KY"), ("Baltimore", "MD"), ("Milwaukee", "WI"),
    ("Albuquerque", "NM"), ("Tucson", "AZ"), ("Fresno", "CA"),
    ("Mesa", "AZ"), ("Sacramento", "CA"), ("Atlanta", "GA"),
    ("Kansas City", "MO"), ("Colorado Springs", "CO"), ("Omaha", "NE"),
    ("Raleigh", "NC"), ("Miami", "FL"), ("Virginia Beach", "VA"),
    ("Long Beach", "CA"), ("Oakland", "CA"), ("Minneapolis", "MN"),
    ("Tulsa", "OK"), ("Tampa", "FL"), ("Arlington", "TX"),
    ("New Orleans", "LA"), ("Wichita", "KS"), ("Cleveland", "OH"),
    ("Bakersfield", "CA"), ("Aurora", "CO"), ("Anaheim", "CA"),
    ("Honolulu", "HI"), ("Santa Ana", "CA"), ("Riverside", "CA"),
    ("Corpus Christi", "TX"), ("Lexington", "KY"), ("Stockton", "CA"),
    ("St. Louis", "MO"), ("Pittsburgh", "PA"), ("Cincinnati", "OH"),
    ("Anchorage", "AK"), ("Henderson", "NV"), ("Greensboro", "NC"),
    ("Plano", "TX"), ("Newark", "NJ"), ("Lincoln", "NE"),
    ("Orlando", "FL"), ("Irvine", "CA"), ("Toledo", "OH"),
    ("Jersey City", "NJ"), ("Chula Vista", "CA"), ("Fort Wayne", "IN"),
    ("St. Petersburg", "FL"), ("Laredo", "TX"), ("Norfolk", "VA"),
    ("Madison", "WI"), ("Lubbock", "TX"), ("Chandler", "AZ"),
    ("Buffalo", "NY"), ("Gilbert", "AZ"), ("Glendale", "AZ"),
    ("Reno", "NV"), ("Winston-Salem", "NC"), ("North Las Vegas", "NV"),
    ("Irving", "TX"), ("Chesapeake", "VA"), ("Hialeah", "FL"),
    ("Garland", "TX"), ("Scottsdale", "AZ"), ("Baton Rouge", "LA"),
    ("Fremont", "CA"), ("Richmond", "VA"), ("Boise", "ID"),
    ("San Bernardino", "CA"), ("Spokane", "WA"), ("Des Moines", "IA"),
    ("Modesto", "CA"), ("Tacoma", "WA"), ("Fontana", "CA"),
    ("Moreno Valley", "CA"), ("Santa Clarita", "CA"), ("Birmingham", "AL"),
    ("Rochester", "NY"), ("Oxnard", "CA"), ("Fayetteville", "NC"),
    ("Aurora", "IL"), ("Glendale", "CA"), ("Huntington Beach", "CA"),
    ("Salt Lake City", "UT"), ("Grand Rapids", "MI"), ("Amarillo", "TX"),
    ("Yonkers", "NY"), ("Montgomery", "AL"), ("Akron", "OH"),
    ("Little Rock", "AR"), ("Huntsville", "AL"), ("Augusta", "GA"),
    ("Grand Prairie", "TX"), ("Columbus", "GA"), ("Tallahassee", "FL"),
    ("Peoria", "IL"), ("Knoxville", "TN"), ("Overland Park", "KS"),
    ("Brownsville", "TX"), ("Vancouver", "WA"), ("Providence", "RI"),
    ("Newport News", "VA"), ("Chattanooga", "TN"), ("Fort Lauderdale", "FL"),
    ("Rancho Cucamonga", "CA"), ("Oceanside", "CA"), ("Santa Rosa", "CA"),
    ("Garden Grove", "CA"), ("Elk Grove", "CA"), ("Pembroke Pines", "FL"),
    ("Salem", "OR"), ("Eugene", "OR"), ("Corona", "CA"),
    ("Cary", "NC"), ("Springfield", "MO"), ("Fort Collins", "CO"),
    ("Jackson", "MS"), ("Alexandria", "VA"), ("Hayward", "CA"),
    ("Lancaster", "CA"), ("Salinas", "CA"), ("Palmdale", "CA"),
    ("Springfield", "MA"), ("Macon", "GA"), ("Kansas City", "KS"),
    ("Sunnyvale", "CA"), ("Pomona", "CA"), ("Killeen", "TX"),
    ("Escondido", "CA"), ("Pasadena", "TX"), ("Naperville", "IL"),
    ("Bellevue", "WA"), ("Joliet", "IL"), ("Murfreesboro", "TN"),
    ("Midland", "TX"), ("Rockford", "IL"), ("Savannah", "GA"),
    ("Bridgeport", "CT"), ("Syracuse", "NY"), ("McAllen", "TX"),
    ("Pasadena", "CA"), ("Paterson", "NJ"), ("Surrey", "ND"),
    ("Lakewood", "CO"), ("Mesquite", "TX"), ("Sunny Isles", "FL"),
    ("Dayton", "OH"), ("Carrollton", "TX"), ("Hampton", "VA"),
    ("McKinney", "TX"), ("Clarksville", "TN"), ("Columbia", "SC"),
    ("Waco", "TX"), ("Sterling Heights", "MI"), ("West Valley City", "UT"),
    ("Cedar Rapids", "IA"), ("New Haven", "CT"), ("Stamford", "CT"),
    ("Concord", "CA"), ("Thousand Oaks", "CA"), ("Elizabeth", "NJ"),
    ("Roseville", "CA"), ("Gainesville", "FL"), ("Visalia", "CA"),
    ("Simi Valley", "CA"), ("Independence", "MO"), ("Hartford", "CT"),
    ("Denton", "TX"), ("Frisco", "TX"), ("Coral Springs", "FL"),
    ("Ann Arbor", "MI"), ("Cleveland Heights", "OH"), ("Abilene", "TX"),
    ("Evansville", "IN"), ("Vallejo", "CA"), ("Allentown", "PA"),
    ("Norman", "OK"), ("Beaumont", "TX"), ("Wilmington", "NC"),
    ("Arvada", "CO"), ("Provo", "UT"), ("Lansing", "MI"),
    ("Odessa", "TX"), ("Richardson", "TX"), ("Round Rock", "TX"),
    ("Cambridge", "MA"), ("Menifee", "CA"), ("West Jordan", "UT"),
    ("Clearwater", "FL"), ("Billings", "MT"), ("Westminster", "CO"),
    ("Manchester", "NH"), ("Lowell", "MA"), ("Antioch", "CA"),
    ("Palm Bay", "FL"), ("Pueblo", "CO"), ("Pearland", "TX"),
    ("College Station", "TX"), ("Waterbury", "CT"), ("El Monte", "CA"),
    ("North Charleston", "SC"), ("Carlsbad", "CA"), ("Downey", "CA"),
    ("Clovis", "CA"), ("Costa Mesa", "CA"), ("High Point", "NC"),
    ("Murrieta", "CA"), ("Inglewood", "CA"), ("Miami Gardens", "FL"),
    ("Elgin", "IL"), ("Wilmington", "DE"), ("Fargo", "ND"),
    ("Gresham", "OR"), ("Broken Arrow", "OK"), ("Burbank", "CA"),
    ("Sandy Springs", "GA"), ("Green Bay", "WI"), ("Tyler", "TX"),
    ("League City", "TX"), ("Boulder", "CO"), ("Davie", "FL"),
    ("Greeley", "CO"), ("San Mateo", "CA"), ("Edinburg", "TX"),
    ("South Bend", "IN"), ("Wichita Falls", "TX"), ("Jurupa Valley", "CA"),
    ("Dearborn", "MI"), ("Livonia", "MI"), ("Sparks", "NV"),
    ("Lakeland", "FL"), ("Rialto", "CA"), ("Allen", "TX"),
    ("West Covina", "CA"), ("Norwalk", "CA"), ("Sandy", "UT"),
    ("Vacaville", "CA"), ("Spokane Valley", "WA"), ("Bend", "OR"),
    ("Rio Rancho", "NM"), ("Charleston", "SC"), ("Orem", "UT"),
    ("Vista", "CA"), ("Renton", "WA"), ("Edison", "NJ"),
    ("Woodbridge", "NJ"), ("Tuscaloosa", "AL"), ("San Angelo", "TX"),
    ("Kenosha", "WI"), ("Boca Raton", "FL"), ("Meridian", "ID"),
]

assert len(TOP_250_CITIES) == 250, f"Expected 250, got {len(TOP_250_CITIES)}"
