"""Compiled charge classification regex rules."""
from __future__ import annotations

import re
from typing import List, Tuple

# (category, patterns) — first match wins; order = priority (more specific first)
_RULES: List[Tuple[str, List[str]]] = [
    (
        "homicide",
        [
            r"\bmurder\b", r"\bhomicide\b", r"\bmanslaughter\b",
            r"\bvoluntary\s+manslaughter\b", r"\binvoluntary\s+manslaughter\b",
            r"\bvehicular\s+homicide\b", r"\bcriminal\s+homicide\b",
            r"\bmurd", r"\bmud+er\b", r"\bmrd+er\b",
            r"\bvolun\s+mansl", r"\bdeath\s+by\s+vehicle",
        ],
    ),
    (
        "sex_crimes",
        [
            r"\brape\b", r"\bsexual\s+assault\b", r"\bsex\s+offense\b",
            r"\bsex\s+offenc", r"\bsexual\s+abuse\b", r"\bsexual\s+battery\b",
            r"\bindecent\s+(libert|expos|assault|act)",
            r"\bindecency\b", r"\bindency\b",
            r"\blewd\b", r"\blewdness\b", r"\bopen\s+lewd",
            r"\bchild\s+mol", r"\bmolest", r"\bsodomy\b",
            r"\binvoluntary\s+deviate\b", r"\bdeviate\s+sexual\s+intercourse\b",
            r"\bdeviatesexual\s+intercourse\b", r"\bidsi\b",
            r"\bsexual\s+intercourse\b", r"\bcarnal\s+knowledge\b",
            r"\bgross\s+sexual\s+imposition\b", r"\bsexual\s+imposition\b",
            r"\bcriminal\s+sexual\s+conduct\b", r"\bcsc\s*\d", r"\bcsc\b",
            r"\bsexual\s+contact\b", r"\babusive\s+sexual\s+contact\b",
            r"\bsexual\s+indecen", r"\bpublic\s+(?:sexual\s+)?indecen",
            r"\bcorruption\s+of\s+(a\s+)?minors?\b",
            r"\bunlawful\s+contact\s+with\s+(a\s+)?minor",
            r"\bvoyeur", r"\bpeeping\b", r"\bbestiality\b", r"\bimportun",
            r"\bcontinuous\s+sexual", r"\bsexual\s+performance\b",
            r"\bstatutory\s+sexual", r"\bsex(?:ual)?\s+seduction\b",
            r"\bsex\s+w/?\s*mnr", r"\bsex(?:ual)?\s+with\s+(a\s+)?min",
            r"\bpornograph", r"\bchild\s+porn", r"\bcsam\b",
            r"\bobscene\s+(?:matter|material)", r"\btransmitting\s+obscene",
            r"\btrans\s*/\s*dstrbtn\s+mat", r"\bmat(?:erial)?\s+dep(?:ict|i)\.?\s*child",
            r"\bprostitution\b", r"\bpatroniz\w*\s+prostitut",
            r"\bsex\s+traffick", r"\bhuman\s+traffick",
            r"\bsolicit\w*\s+.*(sex|prostitu|minor)", r"\bpandering\b",
            r"\bonline\s+solicit(?:ation)?\s+(?:of\s+)?(?:a\s+)?minor",
            r"\bsolicit(?:ation)?\s+(?:of\s+)?(?:a\s+)?(?:minor|child)\b",
            r"\binvasion\s+of\s+privacy.*(sex|intimate)",
            r"\bunlawful\s+sexual", r"\bsexual\s+conduct",
            r"\bforcible\s+fondl", r"\bfondling\b", r"\bfondl",
            r"\bsex\s+crime", r"\bsexually\s+violent",
            r"\bsex(?:ual)?\s+motivat",
            r"\bfailure\s+to\s+register.*(sex|offender)",
            r"\bsex\s+offender", r"\bregistry.*(sex|offender)",
            r"\benticing\s+a\s+(child|minor)", r"\bluring\s+a\s+minor",
            r"\bcoercion.*(?:sex|force).*sex", r"\bentice\w*.*illegal\s+sexual",
            r"\b21\.11\b", r"\b3123\b", r"\b288\b", r"\b261(?:\.5)?\b",
            r"\b18\s*usc\s*224[0-9]", r"\b18\s*usc\s*2422",
            r"\b13a-6-11[01]\b", r"\b13a-6-6[0-9]\b",
            r"\b5-14-1[0-9]{2}\b", r"\b200\.368\b", r"\b201\.23\b",
            # NC/IL jail abbreviations (match expanded forms: SEX→Sexual, AGG→Aggravated)
            r"\bpred\s+crim\s+sex", r"\bsex(?:ual)?\s+offender\s+regis",
            r"\bsex(?:ual)?\s+off.*fail", r"\baggr(?:avated)?\s+sex(?:ual)?\s+aslt",
            r"\bcrim\s+sex(?:ual)?\s+aslt", r"\bsex(?:ual)?\s+exploit",
            r"\bcrime\s+against\s+nature", r"\bsexually\s+dangerous",
            r"\bsexual\s+offense\s+\d", r"\bsex(?:ual)?\s+aslt\b",
            r"\bsol\s+sex\s+by\s+computer", r"\bsex(?:ual)?\s+offse\s+sub",
            r"\bviolent\s+off.*fail\s+regis", r"\bincest\b",
            r"\bmaterial\s+harmful\s+to\s+minors",
            r"\bfail.*register.*sex(?:ual)?\s+off",             r"\bsex(?:ual)?\s+off.*register",
            r"\bfail.*comply.*sex(?:ual)?\s+off",               r"\bsex(?:ual)?\s+off.*(?:rept|report|comply)",
            r"\bsexoff", r"\bsex(?:ual)?\s+offender.*(?:false|child|premises|school)",
            r"\bchild\s+sex(?:ual)?\s+offender", r"\bforcible\s+sex",
            r"\bindec(?:ent)?\s+(?:w|sol).*child", r"\bgrooming\b",
            r"\btravel.*meet.*minor", r"\bcyberstalk",
            r"\bindec(?:ent)?\s+(?:sol|pred)",
            r"\bcrim(?:inal)?\s+sex(?:ual)?\s+ab", r"\bstat(?:utory)?\s+sex",
            r"\bsex(?:ual)?\s+off(?:ense|n)?\s*w/?\s*child",
            r"\bnonconsensual.*(?:sex|image)", r"\bdisclosure.*private\s+image",
            r"\bdissem.*harm.*mater.*minor",
        ],
    ),
    (
        "robbery",
        [
            r"\brobbery\b", r"\barmed\s+robbery\b", r"\bcarjack",
            r"\bstrong.?arm\b", r"\bvehicular\s+hijack",
        ],
    ),
    (
        "burglary_be",
        [
            r"\bburglar", r"\bb\s*&\s*e\b", r"\bb\s+and\s+e\b",
            r"\bbreaking\s+and\s+enter", r"\bbreak\s+and\s+enter",
            r"\bbreaking\s+and\s+or\s+enter", r"\bbreaking\s+or\s+enter",
            r"\bbreak\s*/\s*enter", r"\bbreak/?enter",
            r"\bunlawful\s+entry\b", r"\bhome\s+invasion\b",
            r"\benter(ing)?\s+(a\s+)?(dwell|build|struct)",
            r"\bburglary\s+tools\b",
            r"\bburg\s+habit", r"\bcrim\s+tres.*res.*pers",
            r"\bburg.*habit", r"\bburg\s+bldg", r"\bburg\s+hab\b",
        ],
    ),
    (
        "weapons",
        [
            r"\bfirearm", r"\bhandgun\b", r"\brifle\b", r"\bshotgun\b",
            r"\bweapon", r"\bgun\b", r"\bammunition\b", r"\bconcealed\s+carry",
            r"\bunlawful\s+poss.*weapon", r"\bposs.*firearm",
            r"\bbrandish", r"\bdeadly\s+weapon", r"\bknife\b",
            r"\bexplosive", r"\bdestructive\s+device",
            r"\buuw\b", r"\bfoid\b", r"\bwpn\b", r"\bfelon.*poss.*wpn",
            r"\bfelon.*(?:firearm|f\s*/?\s*arm)",
        ],
    ),
    (
        "domestic",
        [
            r"\bdomestic\b", r"\bfamily\s+violence\b", r"\bfamily\s+abuse\b",
            r"\bintimate\s+partner", r"\bprotection\s+order",
            r"\brestraining\s+order", r"\bviolat.*(protect|restrain)",
            r"\bdomestic\s+assault", r"\bdomestic\s+batter",
            r"\basslt\s+cbi\s+fv\b", r"\bcbi\s+fv\b",
            r"\babuse\s+spousal\b", r"\bspousal\s+abuse\b",
            r"\bbat\s*:\s*spouse", r"\bbattery\s+spouse",
            r"\bchild\s+abuse\b", r"\bchild\s+endanger", r"\bneglect\s+of\s+child",
            r"\belder\s+abuse\b",
            r"\b273\.5\b", r"\bcorp(?:oral)?\s+inj(?:ury)?.{0,20}\b(spouse|cohab)",
            r"\binf\s+corp\s+inj",
            r"\bvio\s+order.*prior\s+vio", r"\bviolat.*order.*prior\s+viol",
            r"\baslt\s+fam", r"\bexploit\s+elder",
        ],
    ),
    (
        "violent",
        [
            r"\bassault\b", r"\bbatter(?:y|ing)\b", r"\baggravated\s+assault",
            r"\bfelonious\s+assault", r"\bstalking\b", r"\bharass",
            r"\bkidnap", r"\bfalse\s+imprison", r"\bunlawful\s+restraint",
            r"\bunl\s+restraint", r"\basslt\b", r"\bstrangul",
            r"\bterroristic\s+threat", r"\bthreat\s+to\s+(kill|injure)",
            r"\bmens?\s+rea.*assault", r"\bmayhem\b", r"\briot\b",
            r"\bresist(ing)?\s+(arrest|officer)", r"\baffray\b",
            r"\bintimidation\b", r"\bmalicious\s+wound",
            r"\btouch\s*(?:or|/|&)\s*strike\b",
            r"\bstrike\s*(?:or|/|&)\s*touch\b",
            # NC/IL jail abbreviations (match expanded forms too)
            r"\bawdw", r"\baggr(?:avated)?\s+aslt", r"\baslt\s+peace\s+off",
            r"\bcommunicating\s+threats", r"\bmenacing\b",
            r"\bfelonious\s+restraint", r"\bmalicious.*wound",
            r"\bserious\s+inj.*vehicle",             r"\bhit\s*(?:/|\s+)\s*run",
            r"\bmissile\s+into\s+dwelling", r"\bthreaten\s+public\s+official",
            r"\bmob\s+action", r"\bcruelty\s+to\s+animal",
            r"\bmalicious.*inj.*prop", r"\bwanton\s+inj",
            r"\bwill.*want.*inj.*prop",
            r"\baslt\s+public\s+servant", r"\breckless\s+conduct",
            r"\bhrsm?t.*threaten", r"\bdisarm.*off",
            r"\bcommunicate.*detain.*witness",
            r"\baslt.*(?:law\s+off|pub\s+serv)", r"\barm\s+terror",
            r"\binjury\s+to\s+child", r"\bintimidate\s+witness",
        ],
    ),
    (
        "drugs",
        [
            r"\bcontroll?ed\s+substance", r"\bnarcotic", r"\bdrug\b",
            r"\bcocaine\b", r"\bheroin\b", r"\bfentanyl\b", r"\bmeth(amphetamine)?\b",
            r"\bmarijuana\b", r"\bcannabis\b", r"\bposs(ession)?\s+of\s+.*(drug|marij|cocaine|heroin|meth|fentanyl|opium|opioid)",
            r"\bpossess.*cds\b", r"\bcds\b", r"\bdelivery\s+of\b",
            r"\btraffick.*drug", r"\bdrug\s+traffick", r"\bintent\s+to\s+(distrib|deliver|sell)",
            r"\bparaphernalia\b", r"\bpwid\b",
            r"\bdrug\s+equip(?:ment)?", r"\bequip(?:ment)?\s*[-–—/]?\s*possess",
            r"\bman\.?\s*delv", r"\bman(?:ufacture)?\s*/?\s*del(?:iv(?:ery)?)?",
            r"\bposs\.?\s+cont\.?\s+sub", r"\bcont\.?\s+subs?\b",
            r"\bposs\s+cs\b", r"\bposs\s+marij",
            # NC schedule system + IL/FL jail shorthand (match expanded forms)
            r"\bsched(?:ule)?\s+[ivx]+\b", r"\bposs(?:ession)?\s+amt\s+con(?:t(?:rol(?:led)?)?)?\s+sub(?:stance)?",
            r"\bmanu(?:facture)?\s*(?:/|\s+)\s*del", r"\bdel(?:ivery)?\s*(?:/|\s+)\s*sell",
            r"\bposs(?:ess(?:ion)?)?\s+wits?\b",
            r"\bmaint.*place.*cont(?:roll?ed)?", r"\bcont(?:roll?ed)?\s+sub(?:s|stance)?\s+act",
            r"\bsell\s+(cont(?:roll?ed)?|sched)", r"\bmanuf.*sched",
            r"\blook-?alike\s+sub", r"\btraffick.*sched",
            r"\bposs(?:ess(?:ion)?)?\s+sched(?:ule)?", r"\bmanufacture\s+sched",
            r"\banhydrous\s+ammonia", r"\becstacy\b", r"\blsd\b",
            r"\bmorphine\b", r"\bphencyclidine\b", r"\bpsylocibin",
            r"\bposs(?:ess(?:ion)?)?\s+cont(?:rol(?:led)?)?\s+sub(?:s|stance)?",
            r"\bcontl\s+sub", r"\bs\s+d\s+contl",
            r"\bposs(?:ess(?:ion)?)?\s+precursor",
            r"\btraffick.*cont(?:roll?ed)?", r"\becs?tasy",
            r"\bmanufacture\s+cont(?:rol)?", r"\bsniffing\s+glue",
            r"\bposs(?:ess)?.*pills?\s+ecs?tasy",
        ],
    ),
    (
        "dui_traffic",
        [
            r"\bdui\b", r"\bdwi\b", r"\bowi\b", r"\bovi\b",
            r"\bdriving\s+under\s+the\s+influence", r"\bdriving\s+while\s+intoxic",
            r"\bimpaired\s+driving", r"\bbac\b", r"\bblood\s+alcohol",
            r"\breckless\s+driving", r"\bspeeding\b", r"\bhit\s+and\s+run",
            r"\bleave\s+the\s+scene", r"\bno\s+license\b", r"\bsuspended\s+license",
            r"\bno\s+valid\s+(?:driver'?s?\s+)?license",
            r"\bno\s+driver'?s?\s+license",
            r"\bdriving\s+without\s+(?:a\s+)?(?:valid\s+)?(?:driver'?s?\s+)?license",
            r"\bno\s+operator", r"\brevoked\s+license",
            r"\btraffic\b", r"\bmv\s+offense", r"\bvehicle\s+code",
            r"\buninsured\s+(motor|vehicle)", r"\belude|eluding\b",
            # NC/IL/FL jail shorthand (match expanded forms: W/ → W, slashes removed)
            r"\bdriv.*(?:license\s+)?revok", r"\bdriving\s+w\s+(?:/\s*)?(suspend|revoke)",
            r"\bdriv.*license\s+perm\s+rvk", r"\boperat.*vehicle.*w\s*(?:/|\s)?\s*o\s+license",
            r"\bmisc.*motor\s+vehicle", r"\boper.*m\.?v\.?without.*fin",
            r"\bdriving\s+w\s+suspend", r"\bdriving\s+w\s+revoke",
            r"\bdriv\s+license\s+revok", r"\bfailure\s+report\s+accident",
            r"\bviolate\s+vehicle\s+registration",
            r"\baggr(?:avated)?\s+fleeing", r"\bevading\s+arrest",
            r"\bdriving\s+revoked", r"\bfailure\s+to\s+stop\s+for\s+accident",
            r"\bfail.*heed.*light.*siren", r"\bspeed.*eld.*arst",
            r"\bdriving\s+<\s*21\s+consume",
            r"\bevad.*arr(?:est)?", r"\bfail.*report.*accident",
        ],
    ),
    (
        "fraud_financial",
        [
            r"\bfraud\b", r"\bforgery\b", r"\bidentity\s+theft", r"\bid\s+theft",
            r"\bembezzl", r"\bcounterfeit", r"\bcredit\s+card", r"\bbad\s+check",
            r"\buttering\b", r"\bwelfare\s+fraud", r"\binsurance\s+fraud",
            r"\bmoney\s+launder", r"\bextortion\b", r"\bbribery\b",
            r"\btheft\s+by\s+deception", r"\bfalse\s+pretense",
            # NC/IL jail shorthand (match expanded forms)
            r"\bworthless\s+check", r"\bobt.*prop.*false",
            r"\bcheat.*property", r"\bhot\s+check", r"\bfalse\s+pretens",
            r"\bfiduc.*prop", r"\bmisapp.*fid", r"\bmoney\s+laund",
            r"\bobtain\s+prop.*false", r"\bnegotiat.*worthless",
            r"\bdefraud", r"\bfalse\s+pr.*chts",
            r"\bunlawful\s+poss.*credit", r"\bincome\s+tax",
            r"\buse\s+forged\s+credit",             r"\bcontinuing\s+finance",
            r"\bbad\s+chk", r"\bfraudulent\s+id",
            r"\bid\s+thft", r"\binterfer.*meter", r"\bunauthorized.*title",
        ],
    ),
    (
        "theft_property",
        [
            r"\btheft\b", r"\blarceny\b", r"\bshoplift", r"\bstolen\s+propert",
            r"\breceiv(ing|ed)\s+stolen", r"\bmotor\s+vehicle\s+theft",
            r"\bauto\s+theft", r"\bgrand\s+theft", r"\bpetit\s+theft",
            r"\bpetty\s+theft", r"\bvandal", r"\bcriminal\s+mischief",
            r"\bproperty\s+damage", r"\barson\b", r"\btrespass",
            r"\bunlawful\s+taking",
            # NC/IL jail shorthand (match expanded forms)
            r"\bstolen\s+veh", r"\bpossess.*stolen\s+goods",
            r"\bunauth.*use.*motor.*convey", r"\bconversion\s+by\s+bailee",
            r"\bkeeping\s+hired\s+property", r"\bfail.*return.*rented",
            r"\btamper.*motor\s+vehicle", r"\bmeddling.*motor\s+vehicle",
            r"\bdamage\s+to\s+property", r"\bcrim\.?\s* dmg",
            r"\bburning.*property", r"\borg\s+retail\s+th",
            r"\bsecret\s+prop\s+hinder", r"\bobtain.*property.*worthless",
            r"\bunlawful\s+poss.*(?:driver|veh).*stolen",
            r"\bcrim(?:inal)?\s+damage?\s+prop",
            r"\bcriminal\s+damage", r"\bburning.*building",
            r"\bstolen\s+title", r"\binjure.*house",
        ],
    ),
    (
        "public_order",
        [
            r"\bdisorderly\b", r"\bpublic\s+intoxic", r"\bdrunk\s+in\s+public",
            r"\bloitering\b", r"\bcurfew\b", r"\bnoise\b",
            r"\bobstruct(ing)?\s+(justice|officer|police)",
            r"\bfalse\s+report", r"\bperjury\b", r"\bcontempt\b",
            r"\bfugitive\b", r"\bescape\b", r"\bbail\s+jump",
            r"\bwarrant\b", r"\bprobation\s+viol", r"\bparole\s+viol",
            r"\bopen\s+container", r"\blitter",
            # NC/IL jail shorthand (match expanded forms)
            r"\bhabitual\s+felon", r"\barmed\s+habitual",
            r"\bresist.*obstruc.*officer", r"\bobstruc.*just.*destroy",
            r"\bconspiracy\b", r"\baccessory.*after.*fact",
            r"\bmalicious\s+conduct.*prison", r"\bcontraband.*penal",
            r"\bfelon.*fail.*return.*furlough", r"\binterfering.*emergency",
            r"\bfalse\s+rpt.*police", r"\bfictitious\s+info.*law",
            r"\bprofane\s+language", r"\bprof.*harrss.*threat.*phone",
            r"\bmisuse.*911", r"\bnon-?support", r"\bcontri.*delinq.*minor",
            r"\bschool\s+attend.*law", r"\bemploy\s+sec\s+viol",
            r"\bviolation\s+social\s+services", r"\bout\s+of\s+state\b",
            r"\bobstruct.*gov", r"\bresist.*officer.*injury",
            r"\bviolat.*court\s+order", r"\bviolation\s+of\s+court\s+order",
            r"\bmunicipal\s+ordinance", r"\border\s+of\s+commitment",
            r"\border\s+of\s+arrest", r"\bmittimus", r"\border\s+to\s+incarcerate",
            r"\bconsume.*alch.*<\s*21", r"\bmalt\s+bev.*<\s*21",
            r"\bminor.*poss.*alcohol", r"\bunderage.*consum",
            r"\bunlawful\s+vehicular\s+invasion",
            r"\bfailure\s+to\s+appear", r"\bfta\b",
            r"\bopen\s+cont.*alcohol", r"\bgame\s+law",
            r"\binterfere.*elect.*monitor",             r"\bfoil.*screen\s+test",
            r"\borg\s+crim", r"\bretaliation", r"\bfalse\s+alarm",
            r"\bimmigration\b", r"\bliquor", r"\blocal\s+ordinance",
            r"\bregulation\s+liquor", r"\brefuse.*false.*infor.*officer",
        ],
    ),
]

_COMPILED: List[Tuple[str, List[re.Pattern]]] = [
    (cat, [re.compile(p, re.IGNORECASE) for p in pats]) for cat, pats in _RULES
]
