"""Tier A open-data arrest / booking source definitions."""
from __future__ import annotations

from typing import List

from scraper.config_types import ArrestSource

# Field maps are best-effort and may need tweaks after live schema checks.
SOURCES: List[ArrestSource] = [
    ArrestSource(
        id="la_arrests",
        name="Los Angeles PD Arrests",
        state="CA",
        jurisdiction="Los Angeles",
        scrape_method="socrata",
        socrata_domain="data.lacity.org",
        socrata_dataset_id="amvf-fr72",
        portal_url="https://data.lacity.org/Public-Safety/Arrest-Data-from-2020-to-4-30-2025/amvf-fr72",
        field_map={
            "Report ID": "source_id",
            "ReportID": "source_id",
            "Arrest Date": "arrest_date",
            "Time": "arrest_time",
            "Area Name": "agency",
            "Age": "age",
            "Sex Code": "sex",
            "Descent Code": "race",
            "Charge Group Description": "charge_description",
            "Charge Description": "charge_description",
            "Charge": "statute",
            "Address": "address",
            "LAT": "latitude",
            "LON": "longitude",
        },
        default_row_limit=5000,
        notes=(
            "LAPD open data. Descent codes (A/B/H/O/W/…) rather than full names "
            "in many exports — verify columns live. Primary use: race vs surname "
            "when names appear, or charge/race stats."
        ),
        has_names=False,
        status="verified_bulk",
    ),
    ArrestSource(
        id="chicago_arrests",
        name="Chicago PD Arrests",
        state="IL",
        jurisdiction="Chicago",
        scrape_method="socrata",
        socrata_domain="data.cityofchicago.org",
        socrata_dataset_id="dpt3-jri9",
        portal_url="https://data.cityofchicago.org/Public-Safety/Arrests/dpt3-jri9",
        field_map={
            "CB_NO": "source_id",
            "CASE NUMBER": "case_number",
            "ARREST DATE": "arrest_date",
            "RACE": "race",
            "CHARGE 1 STATUTE": "statute",
            "CHARGE 1 DESCRIPTION": "charge_description",
            "CHARGE 1 TYPE": "charge_level",
            "CHARGE 1 CLASS": "charge_class",
        },
        default_row_limit=5000,
        notes="Public CPD Arrests dataset; detailed name fields may be limited on public export.",
        has_names=False,
        status="verified_bulk",
    ),
    ArrestSource(
        id="seattle_arrests",
        name="Seattle PD Arrest Data",
        state="WA",
        jurisdiction="Seattle",
        scrape_method="socrata",
        socrata_domain="data.seattle.gov",
        socrata_dataset_id="9bjs-7a7w",
        portal_url="https://data.seattle.gov/Public-Safety/SPD-Arrest-Data/9bjs-7a7w",
        field_map={
            "Offense_ID": "source_id",
            "Arrest_Date": "arrest_date",
            "Crime_Against_Category": "charge_level",
            "Offense": "charge_description",
            "Offense_Category": "charge_group",
            "Race": "race",
            "Sex": "sex",
            "Age": "age",
            "Precinct": "agency",
        },
        default_row_limit=5000,
        notes="SPD arrest open data; field names vary by export version.",
        has_names=False,
        status="verified_bulk",
    ),
    ArrestSource(
        id="montgomery_md_arrests",
        name="Montgomery County MD Daily Arrests",
        state="MD",
        jurisdiction="Montgomery County",
        scrape_method="socrata",
        socrata_domain="data.montgomerycountymd.gov",
        socrata_dataset_id="xhwt-7h2h",
        portal_url="https://data.montgomerycountymd.gov/Public-Safety/Daily-Arrests/xhwt-7h2h",
        field_map={
            "Last Name": "last_name",
            "First Name": "first_name",
            "Middle Name": "middle_name",
            "Race": "race",
            "Sex": "sex",
            "Age": "age",
            "Arrest Date": "arrest_date",
            "Arrest Number": "source_id",
            "Charge": "charge_description",
            "Charge Description": "charge_description",
            "City": "city",
            "State": "state",
        },
        default_row_limit=0,
        notes="County daily arrests — typically includes names (strong for misclassification).",
        has_names=True,
        status="verified_bulk",
    ),
    ArrestSource(
        id="king_wa_bookings",
        name="King County WA Adult Jail Bookings",
        state="WA",
        jurisdiction="King County",
        scrape_method="socrata",
        socrata_domain="data.kingcounty.gov",
        socrata_dataset_id="j56h-zgnm",
        portal_url="https://data.kingcounty.gov/",
        field_map={
            "BookingId": "booking_id",
            "Booking Number": "booking_id",
            "Last Name": "last_name",
            "First Name": "first_name",
            "Middle Name": "middle_name",
            "Race": "race",
            "Sex": "sex",
            "Booking Date Time": "booking_date",
            "Release Date Time": "release_date",
            "Charge Description": "charge_description",
            "Facility": "agency",
        },
        default_row_limit=5000,
        notes="Jail bookings open data — names usually present (primary misclass feed).",
        has_names=True,
        status="verified_bulk",
    ),
    ArrestSource(
        id="sf_arrests",
        name="San Francisco Police Incident / Arrest open data",
        state="CA",
        jurisdiction="San Francisco",
        scrape_method="socrata",
        socrata_domain="data.sfgov.org",
        socrata_dataset_id="wg3w-h783",
        portal_url="https://data.sfgov.org/",
        field_map={
            "Incident Number": "source_id",
            "Incident Date": "arrest_date",
            "Incident Description": "charge_description",
            "Incident Category": "charge_group",
            "Police District": "agency",
            "Analysis Neighborhood": "city",
        },
        default_row_limit=5000,
        notes="Often incident-centric; verify whether arrestee names/race are published.",
        has_names=False,
        status="verified_bulk",
    ),
    ArrestSource(
        id="nyc_arrests",
        name="NYPD Arrests (Historic)",
        state="NY",
        jurisdiction="New York City",
        scrape_method="socrata",
        socrata_domain="data.cityofnewyork.us",
        socrata_dataset_id="8h9b-rp9u",
        portal_url="https://data.cityofnewyork.us/Public-Safety/NYPD-Arrests-Data--Historic-/8h9b-rp9u",
        field_map={
            "arrest_key": "source_id",
            "arrest_date": "arrest_date",
            "pd_desc": "charge_description",
            "ofns_desc": "charge_group",
            "law_cat_cd": "charge_level",
            "arrest_boro": "agency",
            "arrest_precinct": "city",
            "age_group": "age",
            "perp_sex": "sex",
            "perp_race": "race",
        },
        default_row_limit=5000,
        notes=(
            "6M+ records 2006-2025. No names (anonymized arrest_key). "
            "Race field: WHITE, BLACK, WHITE HISPANIC, BLACK HISPANIC, "
            "ASIAN/PACIFIC ISLANDER, AMERICAN INDIAN/ALASKAN NATIVE."
        ),
        has_names=False,
        status="verified_bulk",
    ),
]
