"""Named open-data arrest sources (Socrata) — extends config_sources.SOURCES."""
from __future__ import annotations

from typing import List

from scraper.config_types import ArrestSource

NAMED_SOURCES: List[ArrestSource] = [
    ArrestSource(
        id="dallas_arrests",
        name="Dallas PD Arrests (Named)",
        state="TX",
        jurisdiction="Dallas",
        scrape_method="socrata",
        socrata_domain="www.dallasopendata.com",
        socrata_dataset_id="sdr7-6v3j",
        portal_url="https://www.dallasopendata.com/Public-Safety/Arrests/sdr7-6v3j",
        field_map={
            "ArresteeName": "full_name",
            "NickName": "middle_name",
            "Race": "race",
            "Ethnic": "ethnicity",
            "Sex": "sex",
            "Age": "age",
            "AgeAtArrestTime": "age",
            "Height": "height",
            "Weight": "weight",
            "Hair": "hair_color",
            "Eyes": "eye_color",
            "BirthPlace": "birthplace",
            "ArrestDate": "arrest_date",
            "BookingDate": "booking_date",
            "OffenseDesc": "charge_description",
            "ChargeDesc": "charge_description",
        },
        default_row_limit=5000,
        notes="Full names + physical description. Daily updates. No DOB, no photo.",
        has_names=True,
        status="verified_bulk",
    ),
    ArrestSource(
        id="sonoma_ca_bookings",
        name="Sonoma County CA Bookings",
        state="CA",
        jurisdiction="Sonoma County",
        scrape_method="socrata",
        socrata_domain="sonoma-county-ca-us.socrata.com",
        socrata_dataset_id="f6uf-eqmk",
        portal_url="https://sonoma-county-ca-us.socrata.com/Public-Safety/Booking/f6uf-eqmk",
        field_map={
            "First Name": "first_name",
            "Middle Name": "middle_name",
            "Last Name": "last_name",
            "Race": "race",
            "Age": "age",
            "Gender": "sex",
            "Charge": "charge_description",
            "Booking Date": "booking_date",
            "Status": "status",
            "Location": "city",
        },
        default_row_limit=5000,
        notes="Named bookings with race. Daily updates.",
        has_names=True,
        status="verified_bulk",
    ),
    ArrestSource(
        id="norfolk_va_arrests",
        name="Norfolk VA Arrests",
        state="VA",
        jurisdiction="Norfolk",
        scrape_method="socrata",
        socrata_domain="data.norfolk.gov",
        socrata_dataset_id="uxgi-fkzu",
        portal_url="https://data.norfolk.gov/Public-Safety/Arrests/uxgi-fkzu",
        field_map={
            "First Name": "first_name",
            "Last Name": "last_name",
            "Race": "race",
            "Sex": "sex",
            "Charge": "charge_description",
            "Arrest Date": "arrest_date",
            "Height": "height",
            "Weight": "weight",
            "Hair": "hair_color",
            "Eye": "eye_color",
        },
        default_row_limit=5000,
        notes="Named arrests with race + physical descriptors. Daily 24h rolling window.",
        has_names=True,
        status="verified_bulk",
    ),
    ArrestSource(
        id="providence_ri_arrests",
        name="Providence RI Arrests",
        state="RI",
        jurisdiction="Providence",
        scrape_method="socrata",
        socrata_domain="data.providenceri.gov",
        socrata_dataset_id="vank-fyx9",
        portal_url="https://data.providenceri.gov/Public-Safety/Arrests/vank-fyx9",
        field_map={
            "First Name": "first_name",
            "Last Name": "last_name",
            "Race": "race",
            "Ethnicity": "ethnicity",
            "Year of Birth": "year_of_birth",
            "Gender": "sex",
            "Age": "age",
            "Charge": "charge_description",
            "Arrest Date": "arrest_date",
            "Address": "address",
            "City": "city",
            "State": "state",
        },
        default_row_limit=5000,
        notes="Named arrests with race + year of birth. Daily 180-day rolling window.",
        has_names=True,
        status="verified_bulk",
    ),
]
